# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 874bca22fe2ce733764013a717fd62bed2156f7e3ed7cc15245a174534af25ece5b0e1cc91fb9e3a021e84f3acc53415b2582d4cf6410b5f11bd6f62e73c50af

test:
  secret_key_base: a022115d2219593d9a9ee95859ed1c98b69d01f5eb02e9c15c2b3d8551b423daca7cfe970ccc33eb344334e68bb307dbda95c1ce4b013f361a2f2732ed27433d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
